version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: popc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: popc
      POSTGRES_USER: popc
      POSTGRES_PASSWORD: popc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./apps/api/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U popc -d popc"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    container_name: popc-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO bucket creation
  minio-init:
    image: minio/mc:latest
    container_name: popc-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 minioadmin minioadmin;
      mc mb minio/popc-assets --ignore-existing;
      mc anonymous set download minio/popc-assets;
      exit 0;
      "

  # PoPC API
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: popc-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://popc:popc_password@postgres:5432/popc
      LOG_LEVEL: info
      LOG_PRETTY: "false"
      MAX_ASSET_SIZE_BYTES: 104857600
      MAX_CLOCK_SKEW_SECONDS: 300
      DEFAULT_POLICY: default
      CORS_ORIGIN: "*"
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_USE_SSL: "false"
      MINIO_BUCKET: popc-assets
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  default:
    name: popc-network
